spring:
 redis:
  ##哨兵
  sentinel:
    master: mymaster
    nodes:
      - 192.168.0.108:26379
      - 192.168.0.108:26479
      - 192.168.0.108:26579
  password: 123
  ##
  jedis:
    pool:
      ### 连接池最大连接数（使用负值表示没有限制）
      max-active: 9
      ### 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      ### 连接池中的最大空闲连接
      max-idle: 9
      ### 连接池中的最小空闲连接
      min-idle: 0
  ### Redis数据库索引(默认为0)
  database: 0
  ### 连接超时时间（毫秒）
  timeout: 5000
